### ISSUE TITLE
Crashes when folder selected

### ISSUE THREAD

**Issue by matthewblott** [b0o/nvim-tree-preview.lua#1]
As described above. If the preview window is opened and I navigate through the files as soon as a directory is selected it crashes. Here's a screenshot:

![Screenshot 2024-04-28 at 11 27 46](https://github.com/b0o/nvim-tree-preview.lua/assets/1231417/909210ee-e49e-43a5-90f0-85b69d149fef)

Other than that, the plugin is great!

**Comment by b0o** [comment]
Oops. I think the issue is that you’re not on neovim nightly. I am using some new APIs.

**Comment by b0o** [comment]
I will try to make it more backwards compatible tomorrow.

**Comment by matthewblott** [comment]
@b0o Yeah no biggie, I can press escape but it just makes for a smoother experience. Happy to wait :-)

**Comment by b0o** [comment]
Should be fixed, mind giving it a try?

**Comment by matthewblott** [comment]
@b0o This works a treat now, great work thanks :-)
